# Generated by Django 3.1.6 on 2021-02-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(default='/Users/Christian/Desktop/No_image.jpg', upload_to='bookImages')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('genre', models.CharField(default='other', max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('description', models.CharField(blank=True, max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('bio', models.CharField(blank=True, max_length=4000)),
                ('book', models.ManyToManyField(related_name='authors', to='bookdetails.Book')),
            ],
        ),
    ]
