# Generated by Django 3.1.6 on 2021-04-04 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=4000)),
            ],
            options={
                'ordering': ['author'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(default='bookImages/No_image.jpg', upload_to='bookImages')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('Sci-fi', 'Sci-fi'), ('Fantasy', 'Fantasy'), ('Children', 'Children'), ('Non-fiction', 'Non-fiction'), ('Others', 'Others')], default='other', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('description', models.CharField(max_length=4000)),
                ('publisher', models.CharField(default='Unknown', max_length=200)),
                ('release_date', models.DateField(default='Unknown')),
                ('bestseller', models.BooleanField(default=False)),
                ('authors', models.ManyToManyField(related_name='booker', to='bookdetails.Author')),
            ],
        ),
        migrations.CreateModel(
            name='RatingReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=1, max_length=128)),
                ('review', models.CharField(default='Write Review', max_length=128)),
                ('username', models.CharField(default='', max_length=128)),
                ('nickName', models.BooleanField(default=False)),
                ('first_name', models.CharField(default='', max_length=128)),
                ('last_name', models.CharField(default='', max_length=128)),
                ('book_title', models.CharField(default='', max_length=128)),
                ('book', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='bookdetails.book')),
            ],
            options={
                'db_table': 'ratingReview_bookdetails',
                'managed': True,
            },
        ),
    ]
