# Generated by Django 3.1.7 on 2021-03-05 00:03

import bookdetails.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='bookImages/No_image.jpg', upload_to='bookImages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('sci-fi', 'Sci-fi'), ('fantasy', 'Fantasy'), ('children', 'Children'), ('non-fiction', 'Non-fiction'), ('others', 'Others')], default='other', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[bookdetails.models.Book.validate_rating]),
        ),
    ]
