# Generated by Django 3.1.6 on 2021-04-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdetails', '0002_ratingreview_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingreview',
            name='anony',
            field=models.BooleanField(default=False),
        ),
    ]
