# Generated by Django 3.1.7 on 2021-03-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdetails', '0002_auto_20210304_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='release_date',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
