# Generated by Django 3.1.7 on 2021-03-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdetails', '0003_book_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateField(default='Unknown'),
        ),
    ]
