# Generated by Django 3.1.7 on 2021-03-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdetails', '0004_auto_20210304_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='booker', to='bookdetails.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=4000),
        ),
    ]
