# Generated by Django 3.1.7 on 2021-03-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdetails', '0005_auto_20210304_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Sci-fi', 'Sci-fi'), ('Fantasy', 'Fantasy'), ('Children', 'Children'), ('Non-fiction', 'Non-fiction'), ('Others', 'Others')], default='other', max_length=200),
        ),
    ]
