# Generated by Django 3.1.6 on 2021-02-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinelibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='primary',
            field=models.BooleanField(verbose_name=False),
        ),
    ]
