# Generated by Django 3.1.6 on 2021-02-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinelibrary', '0002_auto_20210219_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='primary',
            field=models.BooleanField(verbose_name=True),
        ),
    ]
