# Generated by Django 3.1.6 on 2021-02-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinelibrary', '0003_auto_20210220_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='max',
            field=models.IntegerField(default=0),
        ),
    ]
