# Generated by Django 3.1.6 on 2021-03-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=1, max_length=128)),
                ('review', models.CharField(default='Write Review', max_length=128)),
                ('username', models.CharField(default='', max_length=128)),
            ],
            options={
                'db_table': 'ratingReview_bookrating',
                'managed': True,
            },
        ),
    ]
